config/routes.rb
Rails.application.routes.draw do
	
  get 'sessions/new'
  get 'sessions/create'
  get 'sessions/destroy'
  resources :akuns
  resources :meets do
  	resources :absens
  end

  root 'meets#index'

  get '/signup' => 'users#new'
  post '/users' => 'users#create'
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  get '/logout' => 'sessions#destroy'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/absen.rb
class Absen < ApplicationRecord
  belongs_to :meet
  validates_presence_of :name
end

app/models/administrator.rb
class Administrator < ApplicationRecord
  include Trestle::Auth::ModelMethods
  include Trestle::Auth::ModelMethods::Rememberable
end

app/models/akun.rb
class Akun < ApplicationRecord
	validates :akun, uniqueness: {case_sensitive: false}
	validates_presence_of :name, :akun, :team
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/meet.rb
class Meet < ApplicationRecord
	has_many :absens, dependent: :destroy
end

app/models/user.rb
class User < ApplicationRecord
	has_secure_password
end

app/controllers/absens_controller.rb
class AbsensController < ApplicationController
	before_action :authorize

	def index
		@absen = Absen.all.order(name: :asc)
	end

	def create
		@meet = Meet.find(params[:meet_id])
		@absen = @meet.absens.create(absen_params)
		redirect_to meet_path(@meet)
	end

	def destroy
		@meet = Meet.find(params[:meet_id])
		@absen = @meet.absens.find(params[:id])
		@absen.destroy
		redirect_to meet_path(@meet)
	end

	private

	def absen_params
		params.require(:absen).permit(:name)
	end
end

app/controllers/akuns_controller.rb
class AkunsController < ApplicationController
  before_action :set_akun, only: [:show, :edit, :update, :destroy]

  # GET /akuns
  # GET /akuns.json
  def index
    @akuns = Akun.all.order(team: :asc)
  end

  # GET /akuns/1
  # GET /akuns/1.json
  def show
  end

  # GET /akuns/new
  def new
    @akun = Akun.new
  end

  # GET /akuns/1/edit
  def edit
  end

  # POST /akuns
  # POST /akuns.json
  def create
    @akun = Akun.new(akun_params)

    respond_to do |format|
      if @akun.save
        format.html { redirect_to @akun, notice: 'Akun was successfully created.' }
        format.json { render :show, status: :created, location: @akun }
      else
        format.html { render :new }
        format.json { render json: @akun.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /akuns/1
  # PATCH/PUT /akuns/1.json
  def update
    respond_to do |format|
      if @akun.update(akun_params)
        format.html { redirect_to @akun, notice: 'Akun was successfully updated.' }
        format.json { render :show, status: :ok, location: @akun }
      else
        format.html { render :edit }
        format.json { render json: @akun.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /akuns/1
  # DELETE /akuns/1.json
  def destroy
    @akun.destroy
    respond_to do |format|
      format.html { redirect_to akuns_url, notice: 'Akun was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_akun
      @akun = Akun.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def akun_params
      params.require(:akun).permit(:name, :akun, :team)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	protect_from_forgery with: :exception

	def current_user
		@current_user ||= User.find(session[:user_id]) if session[:user_id]
	end
	
	helper_method :current_user

	def authorize
	    redirect_to '/login' unless current_user
	end
end

app/controllers/meets_controller.rb
class MeetsController < ApplicationController
  before_action :set_meet, only: [:show, :edit, :update, :destroy]

  # GET /meets
  # GET /meets.json
  def index
    @meets = Meet.all.order(pertemuan: :asc)
  end

  # GET /meets/1
  # GET /meets/1.json
  def show
  end

  # GET /meets/new
  def new
    @meet = Meet.new
  end

  # GET /meets/1/edit
  def edit
  end

  # POST /meets
  # POST /meets.json
  def create
    @meet = Meet.new(meet_params)

    respond_to do |format|
      if @meet.save
        format.html { redirect_to @meet, notice: 'Meet was successfully created.' }
        format.json { render :show, status: :created, location: @meet }
      else
        format.html { render :new }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /meets/1
  # PATCH/PUT /meets/1.json
  def update
    respond_to do |format|
      if @meet.update(meet_params)
        format.html { redirect_to @meet, notice: 'Meet was successfully updated.' }
        format.json { render :show, status: :ok, location: @meet }
      else
        format.html { render :edit }
        format.json { render json: @meet.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /meets/1
  # DELETE /meets/1.json
  def destroy
    @meet.destroy
    respond_to do |format|
      format.html { redirect_to meets_url, notice: 'Meet was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_meet
      @meet = Meet.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def meet_params
      params.require(:meet).permit(:pertemuan)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
  	user = User.find_by_email(params[:email])
    
    if user && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to '/'
    else
      redirect_to '/login'
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to '/akuns'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

	def new
		
	end

	def create
		user = User.new(user_params)
		if user.save
			session[:user_id] = user.id
		else
			redirect_to '/signup'
		end
	end

	def user_params
		params.require(:user).permit(:name, :email, :password, :password_confirmation)
	end
end

app/helpers/absens_helper.rb
module AbsensHelper
end

app/helpers/akuns_helper.rb
module AkunsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/meets_helper.rb
module MeetsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/absens/_absen.html.erb
<p>
  <strong>Name :</strong>
  <%= absen.name %>
</p>

<p>
  <%= link_to 'Destroy Absen', [absen.meet, absen],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/absens/_form.html.erb
<%= form_with(model: [ @meet, @meet.absens.build ], local: true) do |form| %>
  	<div class="row">
  		<div class="col-md-3">

		  
		    <%= form.label :name %>
		    <%= form.text_field :name, class: 'form-control' %>
		 
			<div class="row"> 
				<div class="col-md-5">					
			    	<%= form.submit "Save", class: "btn btn-outline-success" %>
			    </div>
			    <div class="col-md-5">
			    	<%= link_to 'Back', meets_path, class: "btn btn-outline-dark" %>
			  		
			    </div>			    	
			</div>
			  
		</div>
	</div>
<% end %>

app/views/akuns/_form.html.erb
<%= form_with(model: akun, local: true) do |form| %>
  <% if akun.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(akun.errors.count, "error") %> prohibited this akun from being saved:</h2>

      <ul>
      <% akun.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>



  <div class="row">
    <div class="col-md-4 ">
      <%= form.label :name %>
      <%= form.text_field :name, class: "form-control" %>

      <%= form.label :akun %>
      <%= form.text_field :name, class: "form-control" %>

      <%= form.label :team %>
      <%= form.text_field :team, class: "form-control" %>

      <div class="row">
        <div class="col-md-4">
          <%= form.submit "Save", class: "btn btn-outline-success" %>  
        </div>
        <div class="col-md-4">
          <%= link_to 'Back', akuns_path, class: "btn btn-outline-dark" %>
        </div>
      </div>

    </div>
  </div>

<% end %>

app/views/akuns/edit.html.erb
<h1>Editing Akun</h1>

<%= render 'form', akun: @akun %>

<%= link_to 'Show', @akun %> |
<%= link_to 'Back', akuns_path %>

app/views/akuns/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Akuns</h1>

<table class="table table-responsive">
  <thead class="table-dark">
    <tr align="center">
      <th>No</th>
      <th>Name</th>
      <th>Akun</th>
      <th>Team</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% i= 0 %>
    <% @akuns.each do |akun| %>
    <% i += 1 %>
      <tr>
        <td><%= "#{i}" %></td>
        <td><%= akun.name %></td>
        <td><%= akun.akun %></td>
        <td><%= akun.team %></td>
        <td><%= link_to 'Show', akun %></td>
        
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Akun', new_akun_path, class: "btn btn-outline-secondary" %>

app/views/akuns/new.html.erb
<h1>New Akun</h1>

<%= render 'form', akun: @akun %>

app/views/akuns/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @akun.name  %>
</p>

<p>
  <strong>Akun:</strong>
  <%= @akun.akun %>
</p>

<p>
  <strong>Team:</strong>
  <%= @akun.team %>
</p>

<%= link_to 'Edit', edit_akun_path(@akun) %> |
<%= link_to 'Back', akuns_path %>


<!-- <button type="button" class="btn btn-primary" data-toggle="modal" data-target="#exampleModal">
  Launch demo modal
</button> -->

<!-- Modal
<div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        ...
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Close</button>
        <button type="button" class="btn btn-primary">Save changes</button>
      </div>
    </div>
  </div>
</div>
 -->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pertemuan</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>

    <% if current_user %>
      Signed in as <%= current_user.name %> | <%= link_to "Logout", '/logout', class: 'btn btn-outline-dark' %>
    <% else %>
      <%= link_to 'Login', '/login', class: 'btn btn-outline-dark' %> | <%= link_to 'Signup', '/signup', class: 'btn btn-outline-dark' %>
    <% end %>
    <div class="container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/meets/_form.html.erb
<%= form_with(model: meet, local: true) do |form| %>
  <% if meet.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(meet.errors.count, "error") %> prohibited this meet from being saved:</h2>

      <ul>
      <% meet.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :pertemuan %>
    <%= form.text_field :pertemuan %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/meets/edit.html.erb
<h1>Editing Meet</h1>

<%= render 'form', meet: @meet %>

<%= link_to 'Show', @meet %> |
<%= link_to 'Back', meets_path %>

app/views/meets/index.html.erb
<p id="notice"><%= notice %></p>

<!-- <h1>Meets <a class="btn btn-outline-dark btn-sm" href="/meets/new" role="button">NEW</a></h1>  -->

<div class="row">
  <div class="col-md-6">
    <table class="table table-responsive">
      <thead class="table-dark">
        <tr align="center">
          <th>Pertemuan</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @meets.each do |meet| %>
          <tr>
            <td><%= meet.pertemuan %></td>
            <td><%= link_to 'Show', meet %> </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/meets/new.html.erb
<h1>New Meet</h1>

<%= render 'form', meet: @meet %>

<%= link_to 'Back', meets_path %>

app/views/meets/show.html.erb
<p id="notice"><%= notice %></p>

 
<h1>Pertemuan :  <%= @meet.pertemuan %></h1>

<div class="row">
	<div class="col-md-6">
		<table class="table table-responsive">
			<thead>
				<tr align="center">
					<th>No</th>
					<th>Name</th>
					<th>Action</th>
				</tr>
			</thead>
			<tbody>
				<% i = 0 %>
				<% @meet.absens.each do |absen| %>
				<% i += 1 %>
					<tr>
						<td><%= "#{i}" %></td>
						<td><%= absen.name %></td>
						<td><%= link_to 'Destroy', [absen.meet, absen],
               method: :delete,
               data: { confirm: 'Are you sure?' } %></td>
					</tr>
				<% end %>
			</tbody>
		</table>
	</div>

	<div class="col-md-6">
		
	</div>	
</div>

<h2>Add Absen : </h2>
		<%= render 'absens/form' %>
		

app/views/users/new.html.erb
<h1>Signup!</h1>

<%= form_for :user, url: '/users' do |f| %>

  Name: <%= f.text_field :name %>
  Email: <%= f.text_field :email %>
  Password: <%= f.password_field :password %>
  Password Confirmation: <%= f.password_field :password_confirmation %>
  <%= f.submit "Submit" %>

<% end %>